# Generated by Django 5.1.2 on 2024-11-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portofolio_site',
            new_name='portfolio_site',
        ),
    ]
